name: timetable
description: "ğŸ“… Customizable, animated calendar widget including day & week views"
version: 0.2.9
homepage: https://github.com/JonasWanke/timetable

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  black_hole_flutter: ^0.3.0
  collection: ^1.15.0
  dartx: ^0.7.0
  meta: ^1.3.0
  pedantic: ^1.11.0
  rxdart: ^0.26.0
  time_machine: ^0.9.16

dev_dependencies:
  flutter_test:
    sdk: flutter
